const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const rooms=[
{id:'registrar',name:"Registrar's Office",type:'Office',floor:'Ground',location:'Ground Floor • R-101',hours:'Mon–Fri • 8:00 AM–5:00 PM',services:'Enrollment records, certificates, academic documents',contact:'Registrar / Campus Information'},
{id:'library',name:'Library',type:'Facility',floor:'2nd',location:'2nd Floor • R-201',hours:'Mon–Sat • 8:00 AM–6:00 PM',services:'Research, circulation, study spaces',contact:'Library Services'},
{id:'computer-lab',name:'Computer Lab',type:'Laboratory',floor:'3rd',location:'3rd Floor • R-302',hours:'Mon–Sat • 8:00 AM–7:00 PM',services:'Computer access and laboratory activities',contact:'CMA / Laboratory Services'},
{id:'cma',name:'CMA Faculty',type:'Faculty Office',floor:'2nd',location:'2nd Floor • R-214',hours:'Mon–Fri • 8:00 AM–5:00 PM',services:'Faculty coordination and academic concerns',contact:'CMA Faculty'},
{id:'admin',name:'Admin Office',type:'Office',floor:'Ground',location:'Ground Floor • R-105',hours:'Mon–Fri • 8:00 AM–5:00 PM',services:'General administrative services',contact:'Administration'},
{id:'student-services',name:'Student Services',type:'Student Service',floor:'Ground',location:'Ground Floor • R-110',hours:'Mon–Fri • 8:00 AM–5:00 PM',services:'Student assistance and campus concerns',contact:'Student Services'}];
const announcements=[{cat:'Academic',time:'Today • 9:00 AM',title:'Campus Academic Services Update',body:'Students are encouraged to check official school channels for current academic service announcements and schedules.'},{cat:'Student Life',time:'Yesterday • 3:30 PM',title:'Student Services Information Desk',body:'The information desk provides assistance for general campus inquiries, office locations, and student services.'},{cat:'Campus',time:'2 days ago • 10:15 AM',title:'Campus Navigation Assistance',body:'InfoBot AI can help users locate offices, classrooms, laboratories, and campus facilities through the interactive map.'}];
const scholarships=[{tab:'Academic',title:'Academic Excellence Scholarship',eligibility:'For qualified students meeting the program’s academic criteria.',deadline:'Check current school announcement',steps:['Review eligibility criteria.','Prepare the required documents.','Submit the application through the designated school process.']},{tab:'Financial',title:'Financial Assistance',eligibility:'For students requiring financial assistance and meeting institutional requirements.',deadline:'Check current school announcement',steps:['Review requirements.','Prepare supporting documents.','Coordinate with the designated office for submission.']},{tab:'Grants',title:'Special Grants',eligibility:'For qualified applicants under applicable special grant programs.',deadline:'Check current school announcement',steps:['Review the grant details.','Confirm eligibility and documents.','Follow the application instructions from the school.']}];
function now(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});$('#date').textContent=d.toLocaleDateString([], {weekday:'long',month:'long',day:'numeric',year:'numeric'})}setInterval(now,1000);now();
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v)showView(v.dataset.view)});
function roomByText(q){q=q.toLowerCase();return rooms.find(r=>q.includes(r.name.toLowerCase())||r.name.toLowerCase().split(' ').some(w=>w.length>4&&q.includes(w)))}
function response(q){const r=roomByText(q);if(r)return {text:`<b>${r.name}</b><br>${r.location}<br><span class="muted">${r.hours}</span><br><br>${r.services}.`,room:r};if(/scholar|grant|financial/.test(q.toLowerCase()))return{text:`I can help you explore the <b>Scholarship Hub</b>, including Academic Excellence, Financial Assistance, and Special Grants. Open the Scholarship Hub for eligibility details, deadlines, and application steps.`};if(/announce|news|update/.test(q.toLowerCase()))return{text:`You can view current campus announcements in the <b>Announcements</b> module. It includes categories, timestamps, search, and detailed information.`};if(/where|locat|map|navigate|room/.test(q.toLowerCase()))return{text:`Tell me the room, office, or facility you want to locate. I can provide its directory details and focus it on the interactive campus map.`};return{text:`I can assist with general non-confidential campus information such as offices, rooms, facilities, scholarships, announcements, services, and navigation. Try asking <b>“Where is the Registrar's Office?”</b>.`}}
function addMsg(text,user=false){const el=document.createElement('div');el.className='msg '+(user?'user':'bot');el.innerHTML=`<div class="avatar">${user?'YOU':'AI'}</div><div><div class="bubble">${text}</div><div class="msg-time">${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</div></div>`;$('#messages').appendChild(el);$('#messages').scrollTop=$('#messages').scrollHeight;return el}
function ask(q){q=q.trim();if(!q)return;addMsg(q,true);const t=document.createElement('div');t.className='msg bot';t.innerHTML='<div class="avatar">AI</div><div class="bubble"><div class="typing"><i></i><i></i><i></i></div></div>';$(':scope',t);$('#messages').appendChild(t);setTimeout(()=>{t.remove();const a=response(q),el=addMsg(a.text);const action=el.querySelector('.bubble');const actions=document.createElement('div');actions.className='msg-actions';actions.innerHTML='<button data-copy>Copy</button><button data-speak>🔊 Speak</button>';if(a.room)actions.innerHTML+=`<button class="map-link" data-focus="${a.room.id}">⌖ View on Map</button>`;action.appendChild(actions);if(a.room){const qr=document.createElement('div');qr.className='qr-wrap';const box=document.createElement('div');qr.appendChild(box);const small=document.createElement('small');small.textContent='Scan to continue on your phone';qr.appendChild(small);action.appendChild(qr);const url=new URL('mobile.html',location.href);url.searchParams.set('room',a.room.id);new QRCode(box,{text:url.href,width:120,height:120,colorDark:'#05251e',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});}},450)}
function focusRoom(id){const r=rooms.find(x=>x.id===id);if(!r)return;showView('map');$$('.room').forEach(x=>x.classList.remove('focus'));const el=$(`.room[data-id="${id}"]`);if(el){el.classList.add('focus');$('#mapPin').classList.add('show');$('#mapTip').textContent=`${r.name} • ${r.location} • ${r.hours}`;el.scrollIntoView({block:'center',behavior:'smooth'})}}
window.focusRoom=focusRoom;
$('#ask').onclick=()=>ask($('#question').value);$('#question').onkeydown=e=>{if(e.key==='Enter'){$('#ask').click();$('#question').value=''}};$('#clearChat').onclick=()=>{$('#messages').innerHTML='';welcome()};$$('.chips button').forEach(b=>b.onclick=()=>ask(b.dataset.q));
function welcome(){addMsg(`Hello! I’m <b>InfoBot AI</b>. Ask me about campus offices, rooms, services, scholarships, announcements, or navigation.`)}welcome();
document.addEventListener('click',e=>{const f=e.target.closest('[data-focus]');if(f)focusRoom(f.dataset.focus);if(e.target.matches('[data-copy]'))navigator.clipboard?.writeText(e.target.closest('.msg').querySelector('.bubble').innerText);if(e.target.matches('[data-speak]')){const x=e.target.closest('.msg').querySelector('.bubble').innerText; speechSynthesis.speak(new SpeechSynthesisUtterance(x))}});
function renderDirectory(q=''){const g=$('#directoryGrid');g.innerHTML=rooms.filter(r=>(r.name+r.type+r.services).toLowerCase().includes(q.toLowerCase())).map(r=>`<article class="info-card glass"><span class="tag gold">${r.type}</span><h3>${r.name}</h3><p><b>${r.location}</b><br>${r.hours}<br>${r.services}<br>${r.contact}</p><div class="meta"><span class="tag ok">● Normal</span></div><div class="card-actions"><button class="primary" data-focus="${r.id}">⌖ Pinpoint on Map</button><button data-details="${r.id}">QR / Details</button></div></article>`).join('')||'<p>No matching directory entry.</p>'}$('#directorySearch').oninput=e=>renderDirectory(e.target.value);renderDirectory();
function renderAnnouncements(q=''){const g=$('#announcementGrid');g.innerHTML=announcements.filter(a=>(a.title+a.body+a.cat).toLowerCase().includes(q.toLowerCase())).map((a,i)=>`<article class="info-card glass"><span class="tag gold">${a.cat}</span><small>${a.time}</small><h3>${a.title}</h3><p>${a.body}</p><div class="card-actions"><button class="primary" data-ann="${i}">Read Details</button><button>♡ Bookmark</button></div></article>`).join('')}$('#announcementSearch').oninput=e=>renderAnnouncements(e.target.value);renderAnnouncements();
function renderScholarships(tab='Academic'){const g=$('#scholarshipGrid');g.innerHTML=scholarships.filter(s=>s.tab===tab).map((s,i)=>`<article class="info-card glass"><span class="tag gold">${s.tab}</span><h3>${s.title}</h3><p><b>Eligibility</b><br>${s.eligibility}<br><br><b>Deadline</b><br>${s.deadline}</p><div class="card-actions"><button class="primary" data-scholar="${scholarships.indexOf(s)}">View Requirements</button></div></article>`).join('')}$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderScholarships(b.dataset.tab)});renderScholarships();
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('open')}$('#modalClose').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('open')};
document.addEventListener('click',e=>{const d=e.target.closest('[data-details]');if(d){const r=rooms.find(x=>x.id===d.dataset.details);modal(`<h2>${r.name}</h2><p><b>${r.location}</b><br>${r.hours}<br><br>${r.services}<br>${r.contact}</p><div class="modal-qr"><div id="qr"></div><small>Scan for mobile directions and directory details.</small></div>`);const u=new URL('mobile.html',location.href);u.searchParams.set('room',r.id);new QRCode($('#qr'),{text:u.href,width:180,height:180})}const a=e.target.closest('[data-ann]');if(a){const x=announcements[a.dataset.ann];modal(`<h2>${x.title}</h2><p>${x.body}</p><p><b>${x.cat}</b> • ${x.time}</p>`)}const s=e.target.closest('[data-scholar]');if(s){const x=scholarships[s.dataset.scholar];modal(`<h2>${x.title}</h2><p><b>Eligibility</b><br>${x.eligibility}</p><p><b>Deadline</b><br>${x.deadline}</p><ol>${x.steps.map(z=>`<li>${z}</li>`).join('')}</ol>`)}});
$$('[data-floor]').forEach(b=>b.onclick=()=>{$$('[data-floor]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.floor;$$('.room').forEach(el=>el.style.opacity=rooms.find(r=>r.id===el.dataset.id).floor===f?'1':'.28');$('#mapTip').textContent=`Showing ${f} Floor locations.`});$('#mapSearch').oninput=e=>{const q=e.target.value.toLowerCase();$('#mapResults').innerHTML=rooms.filter(r=>(r.name+r.location).toLowerCase().includes(q)).map(r=>`<button class="map-result" data-focus="${r.id}"><b>${r.name}</b><small>${r.location}</small></button>`).join('')};
let scale=1;function applyScale(){$('.building').style.transform=`scale(${scale})`}$('#zoomIn').onclick=()=>{scale=Math.min(1.35,scale+.1);applyScale()};$('#zoomOut').onclick=()=>{scale=Math.max(.75,scale-.1);applyScale()};$('#resetMap').onclick=()=>{scale=1;applyScale();$$('.room').forEach(x=>x.classList.remove('focus'));$('#mapPin').classList.remove('show');$('#mapTip').textContent='Select a room to view its location.'};
const roomParam=new URLSearchParams(location.search).get('room');if(roomParam)setTimeout(()=>focusRoom(roomParam),200);
